### PR TITLE
Fixing failed tests for new release

### PR DESCRIPTION
**Pull request by pedrovma**

### CODE REVIEW

**Comment by jGaboardi** [comment]
[Failure](https://github.com/pysal/spreg/actions/runs/3346320361/jobs/5542979777#step:6:474) due to [`numpy.linalg.LinAlgError`](https://numpy.org/doc/stable/reference/generated/numpy.linalg.LinAlgError.html). And it is affecting Windows Py310.

**Comment by jGaboardi** [comment]
Also, the error seems familiar. I've seen it recently, but can't remember where...

**Comment by jGaboardi** [comment]
It's actually [here](https://github.com/pysal/spreg/issues/56#issuecomment-753072024) in #56.

**Comment by pedrovma** [comment]
Any idea why it passed on #99 and suddenly returned?

**Comment by jGaboardi** [comment]
No idea at all for now. Trying rerunning now.

**Comment by pedrovma** [comment]
I tried, but can't replicate the error. I will omit these tests for now until we find out what is going on.

**Pull request merged**
