### PR TITLE
`ruff` format repo

### LINKED ISSUE #150: swap from `black` to `ruff` for formatting
swap from `black` to `ruff` for formatting

### LINKED ISSUE #151: update `pre-commit` -- add `ruff` ; drop `black`
update `pre-commit` -- add `ruff` ; drop `black`

### LINKED ISSUE #152: update `environment.yml`
update `environment.yml`
* install from [`@main`](https://github.com/pysal/spreg/blob/d92edcb95ffbe44e6d79013aa1428b67b1965e4f/environment.yml#L24)

### PR DESCRIPTION
**Pull request by jGaboardi**
This MR:
* formats with repo with `ruff` standards -- ***only formatting -- no functional changes***
* drops `black` and adds `ruff` to `.pre-commit`
* resolves #150 
* resolves #151

### CODE REVIEW

**Comment by knaaptime** [comment]
this looks like a lot of changes, but it's nothing but formatting. Everything's passing. Will wait for @pedrovma's approval, but this is ready to merge

**Review by knaaptime — APPROVED** [review]

**Comment by jGaboardi** [comment]
@pedrovma After this PR is reviewed and merged (like @knaaptime mentioned, it's only formatting changes), I will get started with #155, which will be more involved. However, both standardized formatting and implementing linting will result in a much more maintainable codebase.

**Comment by pedrovma** [comment]
This is great. The issue here is just that several of these files have already been modified in the private GeoDa repo, so some of the new formatting may be lost. But I will do my best to merge them appropriately!
Many thanks, @jGaboardi!

**Comment by jGaboardi** [comment]
> have already been modified in the private GeoDa repo

One thing you can do is also run `ruff format spreg` on the private repo side of things. That will make merging in much less painful later.

**Comment by martinfleis** [comment]
Just a question. Why do you have a private repo instead of developing in public like we do in any other package? It is super hard to make contributions to spreg if we don't know what is the current state of the codebase.

**Comment by lanselin** [comment]
That's by design. Pedro and I made that decision a long time ago to make development more efficient. The focus is on adding new methods and that is done most efficiently between the two of us without the overhead of the standard GitHub protocol. We're the gate keepers, so to speak. When the code is ready, it goes to the open repo, but for any substantive changes/contributions, people should contact us first.

**Comment by martinfleis** [comment]
Fair.

> for any substantive changes/contributions, people should contact us first.

Shall we add a note on that to the Readme, so the contributing process is clear?

**Comment by lanselin** [comment]
Sure, great idea.

**Review by pedrovma — APPROVED** [review]

**Pull request merged**
