### PR TITLE
Version 1.5

### PR DESCRIPTION
**Pull request by pedrovma**
### **Version 1.5**

This new version of pysal/spreg brings several new features, performance enhancements and bug fixes. The main contributors to this new version are Luc Anselin, Pedro Amaral, Renan Serenini and Lisa Singh.

**Updates:**

1-	Introduction of the DGP module

- 	The DGP module allows for the creation of spatial models for specific Data Generation Processes (DGP) to support simulation exercises. These include the creation of error term vectors (classic and spatial), dependent and independent variables, spatially correlated or not, and other elements for OLS, SAR, SLX, SDM, SARAR models, etc.

2-	Introduction of new specification tests
- 	The Koley-Bera (2024) tests for WX and SDM, and their variants, have been included to the diagnostics suite.
- 	The Common Factor Hypothesis test has been added to Spatial Durbin Models (GM and ML).
 
3-	Impact estimation
- 	The estimation of average direct impact (ADI), average indirect impact (AII), and average total impact (ATI) in summary results has been added to models with a spatial lag of the dependent variable.

4-	Endogenous Spatial Regimes estimation
- 	Methods for endogenous spatial regimes estimation based on Anselin and Amaral (2023) have been added, such as OLS_Endog_Regimes and GM_Lag_Endog_Regimes.

5-	A flag to allow for the printing of the table with the coefficients' results and their inference straight in LaTeX format 

6-	Skater_reg now allows for the estimation of Spatial Lag models with a common spatial lag across regimes. A method adapted from Mojena (1977)'s Rule Two has also been introduced to find the optimal number of regimes for the endogenous spatial regimes models.

7-	Several minor performance enhancements and bug fixes.

### CODE REVIEW

**Comment by knaaptime** [comment]
this is great @pedrovma I'm happy to merge this quickly so we can do a release prior to the meta. I presume you don't actually want a full code review :) ? The one thing I can add to this PR is making sure the new functionality is documented. I think most of the changes are to existing functions, so should be picked up by autodoc, but we should add the new functions and classes from `dgp` to the docs for visibility (is there anything else function/class-level that I missed?)

@jGaboardi do you know why this PR isn't triggering tests?

**Comment by jGaboardi** [comment]
> @jGaboardi do you know why this PR isn't triggering tests?

No... usually it gives a warning if something went wrong in the GHA, but there was actually no change to [`unittests.yml`](https://github.com/pysal/spreg/blob/main/.github/workflows/unittests.yml). So I am not sure at all.

**Comment by knaaptime** [comment]
looking closer, it looks like the CI has [been failing](https://github.com/pysal/spreg/actions/runs/9047641604/job/24859851854#step:5:1343) for the last five months, though I don't think it's anything serious. I think there are some precision issues coming from the tests for `Test_SUR_error`, `TestGM_Error_Regimes`, and `TestGMCombo` (I think maybe just cranking down the numpy tolerance?) and it looks like it's having trouble reading the regimes weights file 

`self.w = libpysal.weights.Queen.from_shapefile(nat.get_path("natregimes.shp"))`

**Comment by pedrovma** [comment]
I have no idea why it suddenly started failing. As you can see, it began after a Bump codecov/codecov-action from 3 to 4:
Screenshot 2024-06-24 at 14 57 00

**Comment by jGaboardi** [comment]
Failures likely have to do with #126 from October 2023 & #135 from April 2024.

**Comment by pedrovma** [comment]
Do you know of any way to force-trigger the tests for this PR so I can work on any updated errors?

**Comment by jGaboardi** [comment]
The workflow is only disabled. You can reenable it here:

Screenshot 2024-06-24 at 2 14 26 PM

**Comment by pedrovma** [comment]
Ok, the tests are finally fixed. The failure in [this](https://github.com/pysal/spreg/actions/runs/9652928406/job/26624128694?pr=136) shouldn't be happening as previous functions using the very same line passed. 

@knaaptime , please let me know what else is required for this PR. Many thanks!

**Comment by knaaptime** [comment]
cool, lets merge this. The remaining failure isn't spreg's fault and I can't reproduce in a local 3.11 environment. So lets go with this then debug in a follow up PR, then cut the release

**Pull request merged**
